const artworks = {
    art1: {
        art_head: '/gallerypage/img/work/sp/aw202301.png',
        art_head1: '/gallerypage/img/work/pc/aw202301.png',
        title: 'Cầu Yahagi ở trạm nghỉ Okazaki đường Tokaido',
        year:'1827–30',
        artist: 'Katsushika Hokusai',
        des1:'Tác phẩm "Cầu Yahagi ở trạm nghỉ Okazaki" là một trong những bức tranh nổi tiếng của nghệ sĩ Ukiyo-e Utagawa Hiroshige, được sáng tác vào giữa thế kỷ 19. Bức tranh thuộc bộ sưu tập "53 trạm nghỉ trên đường Tokaido", một trong những tác phẩm kinh điển thể hiện hành trình từ Edo (Tokyo hiện nay) đến Kyoto, nơi du khách có thể thưởng ngoạn phong cảnh và trải nghiệm văn hóa Nhật Bản.',
        des2:'Trong bức tranh, cầu Yahagi nổi bật giữa cảnh vật, với những người đi bộ và xe ngựa đang băng qua. Cây cầu với kiến trúc độc đáo cùng với dòng nước chảy bên dưới tạo nên một bức tranh sống động, phản ánh sự giao thoa giữa thiên nhiên và đời sống con người. Màu sắc tươi sáng và các chi tiết tinh xảo trong tác phẩm cho thấy tài năng của Hiroshige trong việc khắc họa cảnh vật, đồng thời thể hiện vẻ đẹp giản dị nhưng đầy sức sống của vùng quê Nhật Bản.',
        des3:'Bức tranh không chỉ là một tác phẩm nghệ thuật mà còn mang ý nghĩa lịch sử, ghi lại sự phát triển của giao thông và thương mại trên con đường Tokaido, một trong những tuyến đường quan trọng nhất của Nhật Bản thời kỳ Edo. "Cầu Yahagi ở trạm nghỉ Okazaki" không chỉ giúp người xem cảm nhận được vẻ đẹp của thiên nhiên và văn hóa Nhật Bản mà còn là minh chứng cho di sản nghệ thuật phong phú của Ukiyo-e.',
    },
    art2: {
        art_head: '/gallerypage/img/work/pc/aw202202.png',
        art_head1: '/gallerypage/img/work/pc/aw202202.png',
        title: 'Chim bói cá trên cành tuyết',
        year:'1935.',
        artist: 'Ohara Koson',
        des1:'"Chim bói cá trên cành tuyết" (IJsvogel in de sneeuw) là một trong những tác phẩm tiêu biểu của nghệ sĩ Ukiyo-e Ohara Koson, nổi bật trong thể loại tranh khắc gỗ với chủ đề thiên nhiên và động vật. Tác phẩm này được sáng tác vào đầu thế kỷ 20, một thời kỳ mà nghệ thuật Ukiyo-e tiếp tục phát triển và đổi mới, mang đến cái nhìn mới về thế giới xung quanh.',
        des2:'Trong bức tranh, hình ảnh chim bói cá (Ijsvogel) ngồi trên cành cây được bao phủ bởi tuyết trắng tạo nên một bức tranh hài hòa giữa màu sắc và hình khối. Cảnh vật được khắc họa tinh xảo, thể hiện sự tĩnh lặng và thanh bình của mùa đông. Màu sắc tươi sáng và sự tương phản giữa màu xanh của chim và màu trắng của tuyết tạo nên một cảm giác thu hút, đồng thời làm nổi bật vẻ đẹp giản dị của thiên nhiên.',
        des3:'Koson không chỉ là một nghệ sĩ tài năng trong việc khắc họa các loài chim và động vật, mà còn là người biết cách truyền tải cảm xúc qua từng chi tiết. Tác phẩm này không chỉ thể hiện sự yêu thích thiên nhiên mà còn phản ánh mối liên hệ giữa con người và môi trường xung quanh.',
    },
    art3: {
        art_head: '/gallerypage/img/work/pc/aw202104.png',
        art_head1: '/gallerypage/img/work/pc/aw202104.png',
        title: 'Săn cá voi ở Goto tỉnh Hizen',
        year:'1859',
        artist: 'Utagawa Hiroshige',
        des1:'"Săn cá voi ở Goto, tỉnh Hizen" là một tác phẩm nổi bật của nghệ sĩ Ukiyo-e nổi tiếng, Utagawa Kuniyoshi, được sáng tác vào giữa thế kỷ 19. Tác phẩm này không chỉ là một bức tranh mô tả hoạt động săn cá voi mà còn là một tác phẩm nghệ thuật mang tính sử thi, phản ánh sự gan dạ và tài năng của những người đánh bắt cá voi trong bối cảnh biển cả rộng lớn.',
        des2:'Trong bức tranh, Kuniyoshi khắc họa một cảnh tượng hoành tráng với những ngư dân trên thuyền đang chiến đấu với một con cá voi khổng lồ. Các nhân vật được thể hiện với những đường nét mạnh mẽ, thể hiện sức mạnh và sự quyết tâm của họ. Dòng nước biển và bọt sóng được vẽ một cách sống động, tạo ra sự chuyển động mạnh mẽ trong bức tranh.',
        des3:'Màu sắc rực rỡ và chi tiết tinh xảo trong tác phẩm giúp tăng cường cảm giác kịch tính và sức mạnh của cảnh vật. Bên cạnh đó, hình ảnh cá voi không chỉ đại diện cho một loài động vật mà còn biểu trưng cho những thử thách và khó khăn mà con người phải đối mặt trong cuộc sống.',
    },
    art4: {
        art_head: '/gallerypage/img/work/pc/aw202103.png',
        art_head1: '/gallerypage/img/work/pc/aw202103.png',
        title: 'Hoa anh đào nở ở Yoshino',
        year:'1833',
        artist: 'Katsushika Hokusai',
        des1:'"Hoa anh đào nở ở Yoshino" là một trong những tác phẩm nổi tiếng của nghệ sĩ Ukiyo-e Katsushika Hokusai, được sáng tác vào đầu thế kỷ 19. Tác phẩm này thể hiện vẻ đẹp huyền diệu của hoa anh đào – biểu tượng đặc trưng của văn hóa Nhật Bản – trong bối cảnh phong cảnh thiên nhiên lãng mạn.',
        des2:'Trong bức tranh, Hokusai khắc họa cảnh tượng hoa anh đào nở rộ, tỏa hương sắc giữa bầu trời trong xanh và khung cảnh yên bình của núi Yoshino. Hình ảnh những cành hoa anh đào với những cánh hoa mềm mại, hồng nhạt tạo nên sự tươi mới và sinh động, trong khi núi non hùng vĩ ở phía xa tạo ra một sự đối lập tuyệt đẹp. Cách bố trí này không chỉ giúp người xem cảm nhận được vẻ đẹp của hoa mà còn cảm nhận được sự hòa hợp giữa con người và thiên nhiên.',
        des3:'Hokusai sử dụng kỹ thuật in khắc gỗ tinh xảo để thể hiện các chi tiết và màu sắc sống động. Những gam màu nhẹ nhàng, từ hồng của hoa đến xanh của lá, cùng với các đường nét mềm mại trong bức tranh, tạo nên cảm giác thư giãn và thanh bình cho người xem. Tác phẩm không chỉ thể hiện tài năng nghệ thuật của Hokusai mà còn phản ánh tinh thần thưởng thức thiên nhiên của người Nhật.',
    
    },
    art5: {
        art_head: '/gallerypage/img/work/pc/aw202102.png',
        art_head1: '/gallerypage/img/work/pc/aw202102.png',
        title: 'Diễn viên Kabuki',
        year:'1861',
        artist: 'Utagawa Kunisada',
        des1:'Utagawa Kunisada (1786–1865) là một trong những nghệ sĩ Ukiyo-e nổi tiếng nhất của Nhật Bản, đặc biệt được biết đến với các tác phẩm mô tả diễn viên Kabuki. Kabuki là một hình thức nghệ thuật biểu diễn truyền thống của Nhật Bản, nổi bật với trang phục cầu kỳ, biểu cảm mạnh mẽ và phong cách trình diễn đặc trưng.',
        des2:'Tác phẩm "Diễn viên Kabuki" của Kunisada thường thể hiện những khoảnh khắc đỉnh cao trong các vở kịch Kabuki, nơi các diễn viên thể hiện cảm xúc và tính cách của nhân vật qua các động tác và biểu cảm trên khuôn mặt. Những bức tranh của Kunisada không chỉ khắc họa vẻ đẹp của diễn viên mà còn thể hiện tinh thần của các vở kịch mà họ tham gia, từ những cảnh hành động mạnh mẽ đến những khoảnh khắc lãng mạn đầy cảm xúc.',
        des3:'Trong các tác phẩm của mình, Kunisada sử dụng màu sắc rực rỡ và chi tiết tinh xảo để làm nổi bật trang phục và kiểu tóc của diễn viên. Ông cũng khéo léo kết hợp các yếu tố văn hóa, lịch sử và phong cảnh vào tác phẩm của mình, tạo ra một bức tranh sống động và đầy sức hút.',
        
    },
    art6: {
        art_head: '/gallerypage/img/work/pc/aw202101.png',
        art_head1: '/gallerypage/img/work/pc/aw202101.png',
        title: 'Làng Ōiso',
        year:'1833-1834',
        artist: 'Utagawa Hiroshige',
        des1:'"Làng Ōiso" là một trong những tác phẩm nổi tiếng của nghệ sĩ Ukiyo-e Utagawa Hiroshige, thuộc bộ tranh "Tōkaidō Gojusan-tsugi" (53 Trạm dừng chân trên đường Tōkaidō). Bộ tranh này miêu tả 53 địa điểm nổi bật dọc theo con đường Tōkaidō, một trong những con đường quan trọng nhất trong lịch sử Nhật Bản, nối liền Edo (Tokyo hiện đại) với Kyoto.',
        des2:'Trong bức tranh "Làng Ōiso", Hiroshige khắc họa khung cảnh của một ngôi làng nhỏ nằm bên bờ biển, với những cơn mưa nhẹ đang rơi. Cảnh vật được thể hiện với sự tươi sáng và sinh động, thể hiện không chỉ vẻ đẹp của thiên nhiên mà còn cuộc sống thường nhật của người dân nơi đây. Những ngôi nhà truyền thống, cây cối xanh tươi, và núi non xa xăm tạo nên một bức tranh hài hòa, mang lại cảm giác bình yên và tĩnh lặng.',
        des3:'Một trong những điểm đặc sắc trong tác phẩm là cách Hiroshige sử dụng ánh sáng và bóng đổ để tạo chiều sâu cho bức tranh. Ông khéo léo mô phỏng hiệu ứng của ánh sáng và mưa, khiến cho người xem cảm nhận được không khí của một ngày mưa ở Ōiso. Các màu sắc được phối hợp tinh tế, từ xanh của cây cối đến xám của những đám mây, tạo nên sự tương phản và thu hút ánh nhìn.',
        
    },
    art7: {
        art_head: '/gallerypage/img/work/pc/aw201902.png',
        art_head1: '/gallerypage/img/work/pc/aw201902.png',
        title: 'Phù thủy Takiyasha và bộ xương ma quái',
        year:'1840-1847',
        artist: 'Utagawa Kuniyoshi',
        des1:'"Phù thủy Takiyasha và bộ xương ma quái" là một trong những tác phẩm nổi tiếng của nghệ sĩ Ukiyo-e Utagawa Kuniyoshi, được sáng tác vào giữa thế kỷ 19. Tác phẩm này không chỉ thể hiện tài năng nghệ thuật của Kuniyoshi mà còn mang đậm yếu tố thần thoại và truyền thuyết Nhật Bản, thể hiện sự kết hợp giữa yếu tố huyền bí và kịch tính.',
        des2:'Trong bức tranh, Takiyasha, một phù thủy nổi tiếng trong truyền thuyết Nhật Bản, được khắc họa trong tư thế huyền bí, đang thực hiện một nghi lễ huyền bí để triệu hồi một bộ xương ma quái. Hình ảnh của Takiyasha được thể hiện với vẻ đẹp quyến rũ và quyền lực, với trang phục cầu kỳ, tóc dài và biểu cảm mạnh mẽ. Bộ xương ma quái, được gọi là "yōkai", đang hiện lên với những đường nét rõ ràng và sống động, thể hiện sức mạnh và sự đe dọa.',
        des3:'Kuniyoshi khéo léo sử dụng màu sắc và ánh sáng để tạo ra không khí bí ẩn và kịch tính cho tác phẩm. Những gam màu tối, kết hợp với ánh sáng chiếu sáng từ ngọn lửa, tạo nên sự tương phản mạnh mẽ, khiến người xem cảm nhận được sự hồi hộp và kịch tính trong cảnh tượng này. Các chi tiết tinh xảo, từ trang phục của Takiyasha cho đến hình ảnh của bộ xương, thể hiện tay nghề điêu luyện và khả năng sáng tạo của Kuniyoshi.',
        
    },
    art8: {
        art_head: '/gallerypage/img/work/pc/aw201901.png',
        art_head1: '/gallerypage/img/work/pc/aw201901.png',
        title: 'Ôta Harunaga, Phó thống đốc tỉnh Kazusa ',
        stitle:'Thuộc series "Gương Danh Tướng Nước Ta (Honchô meishô kagami)"',
        year:'1858',
        artist: 'Utagawa Yoshikazu',
        des1:'Tác phẩm "Ôta Harunaga, Phó thống đốc tỉnh Kazusa" của nghệ sĩ Ukiyo-e Utagawa Yoshikazu là một ví dụ điển hình cho việc khắc họa nhân vật lịch sử trong nghệ thuật Nhật Bản vào thế kỷ 19. Utagawa Yoshikazu, một nghệ sĩ thuộc trường phái Utagawa, đã nổi bật với khả năng thể hiện các nhân vật trong trang phục truyền thống và bối cảnh văn hóa phong phú của thời kỳ Edo.',
        des2:'Bức tranh này mô tả Ôta Harunaga, một nhân vật lịch sử có vai trò quan trọng trong việc quản lý tỉnh Kazusa. Ông được thể hiện với trang phục quý tộc, với các chi tiết tinh xảo và màu sắc sống động, phản ánh sự quyền quý và uy quyền của một vị phó thống đốc. Cách bố trí hình ảnh của Harunaga trong bức tranh tạo nên một cảm giác mạnh mẽ và quyền lực, đồng thời thể hiện sự tôn kính đối với các nhân vật lịch sử trong văn hóa Nhật Bản.',
        des3:'Yoshikazu sử dụng kỹ thuật in khắc gỗ tinh xảo để tạo ra các đường nét và họa tiết sống động. Các chi tiết như trang phục, kiểu tóc và biểu cảm trên khuôn mặt của Harunaga được thể hiện một cách rõ ràng và sắc nét, cho thấy sự khéo léo trong cách sử dụng ánh sáng và bóng đổ. Màu sắc trong bức tranh cũng rất đa dạng, từ những gam màu sáng nổi bật đến các tông màu trầm hơn, tạo nên một bức tranh hài hòa và bắt mắt.',
        
    },
    art9: {
        art_head: '/gallerypage/img/work/pc/aw201801.png',
        art_head1: '/gallerypage/img/work/pc/aw201801.png',
        title: 'Đền Zojoji',
        artist: 'Kawase Hasui',
        year:'1925',
        des1:'"Đền Zojoji" là một tác phẩm nổi bật của nghệ sĩ Ukiyo-e Kawase Hasui, một trong những người tiên phong trong phong trào in tranh hiện đại tại Nhật Bản vào đầu thế kỷ 20. Tác phẩm này thuộc bộ sưu tập các bức tranh khắc gỗ mô tả các cảnh quan đẹp và các địa điểm nổi tiếng tại Nhật Bản, thể hiện sự kết hợp giữa nghệ thuật truyền thống và cảm xúc hiện đại.',
        des2:'Đền Zojoji là một ngôi đền của Phật giáo Jōdo, một nhánh của Tịnh Độ tông, nằm ở Tokyo. Tác phẩm khắc họa cảnh tượng của ngôi đền với sự kết hợp hoàn hảo giữa kiến trúc và thiên nhiên xung quanh. Trong bức tranh, Hasui đã tạo ra một khung cảnh tuyệt đẹp với ngôi đền được bao quanh bởi cây cối xanh tươi và bầu trời trong xanh. Hình ảnh của ngôi đền được thể hiện với các chi tiết kiến trúc tinh xảo, từ mái vòm uốn cong đến các họa tiết trang trí cầu kỳ, thể hiện kỹ năng và sự chú ý đến từng chi tiết của nghệ sĩ.',
        des3:'Kawase Hasui sử dụng màu sắc một cách tinh tế để truyền tải không khí thanh bình và yên tĩnh của không gian tâm linh. Các tông màu nhẹ nhàng và hài hòa tạo ra cảm giác thư giãn cho người xem, đồng thời giúp làm nổi bật vẻ đẹp của thiên nhiên xung quanh ngôi đền. Bức tranh không chỉ phản ánh vẻ đẹp của kiến trúc mà còn thể hiện mối liên hệ sâu sắc giữa con người và thiên nhiên trong văn hóa Nhật Bản.',
        
    },
    art10: {
        art_head: '/gallerypage/img/work/pc/aw201401.png',
        art_head1: '/gallerypage/img/work/pc/aw201401.png',
        title: 'Gặp mưa ở Shono',
        year:'1833',
        artist: 'Utagawa Hiroshige',
        stitle:'Thuộc series "Năm mươi ba trạm của Tokaido (Hoeido Tokaido)"',
        des1:'"Gặp mưa ở Shono" là một trong những tác phẩm nổi tiếng của nghệ sĩ Ukiyo-e Utagawa Hiroshige, thuộc bộ tranh "Tōkaidō Gojusan-tsugi" (53 Trạm dừng chân trên đường Tōkaidō). Tác phẩm này miêu tả cảnh mưa bão ở trạm dừng Shono, mang đến một cái nhìn đầy nghệ thuật về sức mạnh của thiên nhiên và cuộc sống thường nhật của con người trong thời kỳ Edo.',
        des2:'Trong bức tranh, Hiroshige khéo léo thể hiện cảnh tượng một cơn bão đổ xuống, với những giọt mưa lớn và gió mạnh. Hình ảnh các nhân vật đang di chuyển qua mưa được mô tả sống động, thể hiện sự kiên cường và nhẫn nại của họ trong điều kiện thời tiết khắc nghiệt. Các chi tiết như áo mưa và cách mọi người nép mình dưới những chiếc ô tạo nên cảm giác gần gũi và thực tế, giúp người xem cảm nhận được bầu không khí căng thẳng của cơn bão.',
        des3:'"Gặp mưa ở Shono" không chỉ là một tác phẩm nghệ thuật tuyệt đẹp mà còn là một tài liệu văn hóa quý giá, ghi lại cảnh vật và cuộc sống thường nhật của người dân Nhật Bản trong thời kỳ Edo. Nó phản ánh tâm lý và cách sống của con người đối diện với thiên nhiên, đồng thời thể hiện sự tôn kính đối với vẻ đẹp của phong cảnh Nhật Bản.',
        
    },
    art11: {
        art_head: '/gallerypage/img/work/sp/aw201301.png',
        art_head1: '/gallerypage/img/work/sp/aw201301.png',
        title: 'Chiryū-juku',
        stitle:'Thuộc series "Năm mươi ba trạm của Tokaido (Hoeido Tokaido)"',
        artist: 'Utagawa Hiroshige',
        year:'1830',
        des1:'"Chiryū-juku" là một trong những tác phẩm nổi bật của nghệ sĩ Ukiyo-e Utagawa Hiroshige, thuộc bộ tranh "Tōkaidō Gojusan-tsugi" (53 Trạm dừng chân trên đường Tōkaidō). Tác phẩm này mô tả một trong những trạm dừng chân nổi tiếng dọc theo con đường Tōkaidō, nơi mà các thương nhân, du khách và hành khách thường dừng lại để nghỉ ngơi trong hành trình từ Edo (Tokyo hiện đại) đến Kyoto.',
        des2:'Bức tranh "Chiryū-juku" khắc họa khung cảnh nhộn nhịp của trạm dừng chân, với các nhân vật đang di chuyển qua lại. Hình ảnh của những người lữ khách đang ngồi nghỉ, cùng với các nhà buôn đang giao dịch, tạo nên một bức tranh sống động và đầy sức sống. Hiroshige đã tinh tế mô tả sự hòa hợp giữa con người và thiên nhiên, với cảnh vật xung quanh trạm dừng chân, bao gồm các ngọn núi và cây cối, góp phần tạo nên không gian ấm cúng và thân thiện.',
        des3:'Một trong những điểm nổi bật của tác phẩm là cách Hiroshige sử dụng ánh sáng và màu sắc. Ông đã khéo léo phối hợp các tông màu khác nhau để thể hiện ánh sáng tự nhiên, từ những gam màu sáng của bầu trời cho đến các tông màu tối hơn của cây cối, tạo ra chiều sâu và sự phong phú cho bức tranh. Kỹ thuật này giúp người xem cảm nhận được không khí trong lành và sự tươi mát của một ngày mới.',
        
    },
    art12: {
        art_head: '/gallerypage/img/work/pc/aw201202.png',
        art_head1: '/gallerypage/img/work/pc/aw201202.png',
        title: 'Tuyết đêm ở Kanbara',
        artist: 'Utagawa Hiroshige',
        year:'1833-34',
        des1:'"Tuyết đêm ở Kanbara" là một tác phẩm nổi tiếng của nghệ sĩ Ukiyo-e Utagawa Hiroshige, nằm trong bộ tranh "Tōkaidō Gojusan-tsugi" (53 Trạm dừng chân trên đường Tōkaidō). Tác phẩm này khắc họa vẻ đẹp thanh bình và huyền bí của một đêm tuyết rơi ở Kanbara, mang đến cho người xem cảm giác yên tĩnh và thơ mộng.',
        des2:'Bức tranh mô tả cảnh tượng một con đường dọc theo trạm dừng chân Kanbara, nơi mà lớp tuyết trắng phủ lên mọi thứ, tạo nên một bức tranh kỳ diệu. Những tán cây với những cành cây được bao phủ bởi tuyết trắng, kết hợp với ánh sáng dịu dàng của mặt trăng, tạo ra một không gian ấm cúng và huyền ảo. Hình ảnh của những người lữ khách đang đi bộ qua tuyết, cùng với ánh đèn lồng phát sáng, tạo nên sự sống động và nhân văn trong khung cảnh thanh bình này.',
        des3:'Hiroshige nổi bật với khả năng sử dụng màu sắc và ánh sáng để tạo chiều sâu cho tác phẩm. Ông đã khéo léo phối hợp các tông màu xanh, trắng và xám, cùng với các sắc thái tối tươi sáng, tạo ra sự tương phản mạnh mẽ và cảm giác mát lạnh của mùa đông. Kỹ thuật này giúp bức tranh không chỉ thể hiện được cảnh vật mà còn truyền tải được cảm xúc và tâm trạng của nhân vật trong không gian lạnh lẽo nhưng đẹp đẽ.',
        
    },
    art13: {
        art_head: '/gallerypage/img/work/pc/aw201201.png',
        art_head1: '/gallerypage/img/work/pc/aw201201.png',
        title: 'Bạch miêu',
        artist: 'Watanabe Shotei',
        year:'1924',
        des1:'"Bạch Miêu" (White Cat) là một tác phẩm nổi bật của nghệ sĩ Ukiyo-e Watanabe Shotei, một trong những nghệ sĩ khắc gỗ hàng đầu trong thời kỳ Meiji. Tác phẩm này thể hiện sự yêu mến và tôn vinh vẻ đẹp của động vật, đặc biệt là hình ảnh một chú mèo trắng, biểu tượng cho sự thanh khiết và tinh tế.',
        des2:'Trong bức tranh, Watanabe Shotei khéo léo miêu tả chú mèo trắng đang nằm nghỉ ngơi, với bộ lông mượt mà và ánh mắt đầy sức sống. Cách sử dụng màu sắc trong tác phẩm rất tinh tế, từ những gam màu sáng của bộ lông cho đến những tông màu ấm áp của nền và các chi tiết xung quanh. Hình ảnh của chú mèo được thể hiện một cách sống động và chân thực, phản ánh sự khéo léo và tài năng của nghệ sĩ trong việc ghi lại vẻ đẹp của một khoảnh khắc bình dị trong cuộc sống.',
        des3:'Ngoài việc tôn vinh vẻ đẹp của chú mèo, tác phẩm còn thể hiện một không gian tĩnh lặng và thanh bình. Bức tranh gợi lên cảm giác gần gũi với thiên nhiên và cuộc sống hàng ngày, cho thấy sự quan tâm của Watanabe đối với các chi tiết nhỏ bé trong cuộc sống. Các yếu tố như ánh sáng, bóng đổ và cách bố trí hình ảnh được thực hiện một cách hài hòa, tạo ra một cảm giác ấm cúng và thư giãn cho người xem.',
        
    },
    art14: {
        art_head: '/gallerypage/img/work/pc/aw201003.png',
        art_head1: '/gallerypage/img/work/pc/aw201003.png',
        title: 'Trận chiến ở núi Ishibashi',
        artist: 'Utagawa Yoshikazu',
        year:'1856.',
        des1:'"Trận chiến ở núi Ishibashi" là một tác phẩm nổi bật của nghệ sĩ Ukiyo-e Utagawa Yoshikazu, thuộc thể loại tranh khắc gỗ lịch sử. Tác phẩm này khắc họa một cảnh tượng đầy kịch tính của trận chiến diễn ra tại núi Ishibashi, thể hiện sự hùng tráng và sức mạnh của các chiến binh trong thời kỳ chiến tranh ở Nhật Bản.',
        des2:'Bức tranh diễn tả cảnh tượng hỗn loạn của trận chiến, với các chiến binh mặc giáp đang chiến đấu quyết liệt trên nền núi đá. Yoshikazu đã khéo léo sử dụng các tư thế, biểu cảm và hành động của nhân vật để tạo nên một bức tranh sống động, truyền tải cảm giác căng thẳng và quyết liệt của trận chiến. Hình ảnh những chiến binh mạnh mẽ, với vũ khí trên tay, thể hiện sự dũng cảm và quyết tâm trong cuộc chiến, mang đến cho người xem cảm giác hồi hộp và kích thích.',
        des3:'Màu sắc trong tác phẩm được sử dụng một cách táo bạo và mạnh mẽ. Các tông màu đậm và sáng nổi bật lên hình ảnh các chiến binh, giúp tạo ra sự tương phản với khung cảnh thiên nhiên xung quanh. Yoshikazu đã thành công trong việc sử dụng ánh sáng và bóng đổ để tạo chiều sâu cho bức tranh, từ đó tăng thêm phần kịch tính cho cảnh chiến đấu.',
        
    },
    art15: {
        art_head: '/gallerypage/img/work/pc/aw201002.png',
        art_head1: '/gallerypage/img/work/pc/aw201002.png',
        title: 'Kiso Yoshinaka và Tomoe Gozen',
        artist: 'Utagawa Yoshikazu',
        year:'1857',
        des1:'"Kiso Yoshinaka và Tomoe Gozen" là một tác phẩm nổi bật của nghệ sĩ Ukiyo-e Utagawa Yoshikazu, thể hiện một trong những câu chuyện tình yêu và lòng dũng cảm nổi tiếng trong lịch sử Nhật Bản. Tác phẩm này không chỉ khắc họa mối quan hệ giữa hai nhân vật chính mà còn phản ánh văn hóa samurai và sự tôn vinh các nữ chiến binh trong thời kỳ chiến tranh.',
        des2:'Bức tranh mô tả Kiso Yoshinaka, một trong những vị tướng nổi tiếng trong cuộc nội chiến Genpei, cùng với Tomoe Gozen, một nữ chiến binh dũng mãnh và trung thành. Hình ảnh của họ được thể hiện với các bộ giáp samurai tinh xảo, với Yoshinaka đang cầm kiếm và Tomoe Gozen đứng bên cạnh, sẵn sàng chiến đấu. Yoshikazu đã khéo léo miêu tả sự mạnh mẽ và kiêu hãnh của cả hai nhân vật, đồng thời truyền tải cảm giác tình cảm gắn bó giữa họ.',
        des3:'Màu sắc trong tác phẩm rất ấn tượng, với các tông màu sống động và đậm. Yoshikazu đã sử dụng ánh sáng và bóng đổ để tạo chiều sâu cho bức tranh, làm nổi bật các chi tiết trên trang phục và vũ khí của hai nhân vật. Các yếu tố thiên nhiên xung quanh cũng được mô tả một cách tỉ mỉ, từ cành cây, hoa lá đến các đám mây, tạo nên một bức tranh phong cảnh đầy sức sống.',
        
    },
    art16: {
        art_head: '/gallerypage/img/work/pc/aw201001.png',
        art_head1: '/gallerypage/img/work/pc/aw201001.png',
        title: 'Hoa anh đào bên cổng',
        artist: 'Yoshida Toshi',
        year:'1951',
        des1:'"Hoa anh đào bên cổng" là một tác phẩm nổi bật của nghệ sĩ Ukiyo-e Yoshida Toshi, thể hiện vẻ đẹp thanh bình và lãng mạn của mùa xuân Nhật Bản qua hình ảnh hoa anh đào. Tác phẩm không chỉ là sự tôn vinh của loài hoa biểu tượng này mà còn mang trong mình những giá trị văn hóa sâu sắc.',
        des2:'Bức tranh khắc họa cảnh một cổng truyền thống Nhật Bản, với những cành hoa anh đào nở rộ phủ đầy phía trên. Màu hồng tươi sáng của hoa anh đào tạo nên một sự tương phản rực rỡ với tông màu tối và tự nhiên của cổng, khiến bức tranh trở nên nổi bật và thu hút ánh nhìn. Yoshida Toshi đã khéo léo sử dụng màu sắc để truyền tải sự tươi mới và sức sống của mùa xuân, mang lại cảm giác vui tươi và thư giãn cho người xem.',
        des3:'Bên cạnh hoa anh đào, các chi tiết khác như cổng, cây cối và bầu trời cũng được thể hiện một cách tinh tế. Toshi đã chăm chút từng đường nét, từ hình dáng của cánh hoa đến cách ánh sáng chiếu xuống, tạo ra một không gian tràn đầy nhựa sống và thanh bình. Hình ảnh của những người đi bộ dưới những tán hoa anh đào cũng gợi lên cảm giác gần gũi và thực tế, khiến người xem cảm nhận được vẻ đẹp của một ngày xuân đẹp trời.',
        
    },
    art17: {
        art_head: '/gallerypage/img/work/pc/aw2011011.png',
        art_head1: '/gallerypage/img/work/pc/aw2011011.png',
        title: 'Cầu Benkei',
        artist: 'Kasamatsu Shiro',
        year:'1953.',
        des1:'"Cầu Benkei" là một tác phẩm nghệ thuật nổi bật của nghệ sĩ Ukiyo-e Kasamatsu Shiro, thể hiện vẻ đẹp thơ mộng và yên bình của cảnh quan Nhật Bản thông qua hình ảnh của một cây cầu cổ kính. Tác phẩm này không chỉ khắc họa cảnh vật mà còn gợi lên những câu chuyện lịch sử và văn hóa đậm đà.',
        des2:'Bức tranh mô tả một khung cảnh thanh bình bên dòng sông, với cây cầu Benkei trải dài qua mặt nước, bao quanh là những tán cây xanh tươi và hoa lá. Hình ảnh cây cầu được thể hiện với những chi tiết tinh xảo, từ các cột trụ cho đến các mảng gỗ, thể hiện tài năng khéo léo của Kasamatsu trong việc ghi lại vẻ đẹp của kiến trúc cổ truyền Nhật Bản.',
        des3:'Màu sắc trong tác phẩm rất hài hòa, với sự kết hợp giữa các tông màu xanh lá cây tươi mát của cây cối và những gam màu ấm áp từ ánh sáng mặt trời phản chiếu trên mặt nước. Kasamatsu đã khéo léo sử dụng ánh sáng và bóng đổ để tạo chiều sâu và không gian cho bức tranh, mang lại cảm giác sống động và gần gũi với thiên nhiên.',
        
    },   
};
module.exports = artworks;